{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "flux-kcl-controller.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "flux-kcl-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flux-kcl-controller.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flux-kcl-controller.selectorLabels" . | nindent 6 }}
{{- end }}
