{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flux-kcl-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flux-kcl-controller.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "flux-kcl-controller.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http-prom
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}
